### ISSUE TITLE
Long running task will stop randomly

### ISSUE THREAD

**Issue by shivanraptor** [leesei/heroku-buildpack-casperjs#7]
I use this buildpack to run a long-running CasperJS task with the following command:

    ~$ heroku run casperjs long.js > log.txt

but the task stops randomly, without leaving any error message. Sometimes it ran for few hours, sometimes it ran for few minutes. Is this a potential bug?

**Comment by leesei** [comment]
As this buildpack only *installs* the binary, this should be a bug of your script or `casperjs`.
The process might hit the CPU/memory limit of Heroku and get killed.

Is your script running correctly in a local environment?

You can also manually install casperjs and phantomjs into any Heroku instance and try the script out.
If it can be fixed by the latest version of casperjs and phantomjs, I can do the update.
If the issue can be reproduced, ask about it on [Heroku Forums](https://discussion.heroku.com/).

**Comment by shivanraptor** [comment]
Yes, my script loads correctly in local environment; it runs for 3 days in local and complete without any issues. How can I review whether if I reach Heroku's resource limit ?

Will try to manually install the CasperJS & PhantomJS on Heroku and retry. Thanks for your help.

**Comment by leesei** [comment]
For that you have to consult Heroku forum.
Hope it helps.
